[package]
name = "itp-sgx-crypto"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { version = "0.6.0" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }
log = { version = "0.4", default-features = false }
ofb = { version = "0.4.0" }

sgx_crypto = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", default-features = false }
sgx_serialize = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", default-features = false }

# sgx deps
sgx_rand = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", optional = true }
sgx_tprotected_fs = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", optional = true }
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview" }

# substrate 
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }

# local deps
itp-sgx-io = { path = "../io", default-features = false }

# test sgx deps
itp-sgx-temp-dir = { path = "../temp-dir", default-features = false, optional = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "log/std",
    "itp-sgx-io/std",
    "sp-core/std",
    "sgx_crypto/userialize",
    "sgx_serialize/userialize",
]
sgx = [
    "itp-sgx-io/sgx",
    "sgx_tstd",
    "sgx_tprotected_fs",
    "sgx_rand",
    "sgx_crypto/tserialize",
    "sgx_serialize/tserialize",
]
mocks = []
test = [
    # features
    "mocks",
    "sgx",
    # deps
    "itp-sgx-temp-dir",
]
