[package]
name = "itp-types"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
homepage = 'https://litentry.com/'
repository = 'https://github.com/litentry/litentry-parachain'
license = "Apache-2.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

# local dependencies
ba-itp-utils = { path = "../../core-primitives/utils", default-features = false }
itp-sgx-crypto = { path = "../sgx/crypto", default-features = false }
itp-sgx-runtime-primitives = { path = "../../core-primitives/sgx-runtime-primitives", default-features = false }
itp-stf-primitives = { path = "../../core-primitives/stf-primitives", default-features = false }

# scs
substrate-api-client = { default-features = false, features = ["sync-api"], git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.42-tag-v0.14.0" }

# substrate-deps
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# litentry
litentry-primitives = { path = "../../litentry/primitives", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "itp-sgx-crypto/std",
    "itp-sgx-runtime-primitives/std",
    "itp-stf-primitives/std",
    "ba-itp-utils/std",
    "substrate-api-client/std",
    # substrate
    "frame-system/std",
    "pallet-balances/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    # litentry
    "litentry-primitives/std",
]
test = []
