hard_tabs = true
max_width = 100
use_small_heuristics = "Max"
reorder_imports = true
newline_style = "Unix"
chain_width = 80
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
use_field_init_shorthand = true