[package]
name = "id-itp-enclave-api-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { workspace = true }

[features]
# necessary to run cargo tests without any preliminaries
# See: https://github.com/rust-lang/cargo/issues/2549
link-sgx-libs = []
