[package]
authors = ['Trust Computing GmbH <info@litentry.com>']
description = 'Proc-macros used by Litentry crates.'
name = "litentry-macros"
version = "0.1.0"
edition = "2021"

[features]
development = []
