[litentry-worker]
RUST_LOG="info"
litentry_worker="debug"
ws="info"
sp_io="error"
substrate_api_client="warn"
itc_parentchain_light_client="info"
jsonrpsee_ws_client="warn"
jsonrpsee_ws_server="warn"
enclave_runtime="debug"
id_ita_stf="debug"
its_rpc_handler="warn"
itc_rpc_client="warn"
its_consensus_common="debug"
its_state="warn"
its_consensus_aura="warn"
"aura*"="warn"
its_consensus_slots="warn"
id_itc_direct_rpc_server="debug"
bc_itc_direct_rpc_server="debug"
itp_attestation_handler="debug"
http_req="debug"
lc_mock_server="warn"
itc_rest_client="debug"
lc_credentials="debug"
lc_identity_verification="debug"
lc_stf_task_receiver="debug"
lc_stf_task_sender="debug"
lc_data_providers="debug"
id_itp_top_pool="debug"
bc_itp_top_pool="debug"
id_itc_parentchain_indirect_calls_executor="debug"
bc_itc_parentchain_indirect_calls_executor="debug"
id_itc_direct_rpc_client="debug"
bc_itc_direct_rpc_client="debug"
id_itp_top_pool_author="debug"
bc_itp_top_pool_author="debug"
bc_musig2_runner="debug"
bc_musig2_ceremony="debug"
bc_task_receiver="debug"

[litentry-cli]
RUST_LOG="debug"
ws="info"
sp_io="warn"
substrate_api_client="warn"
enclave="debug"
