services:
    lit-sign-bitcoin:
        image: litentry/bitacross-cli:latest
        container_name: litentry-sign-bitcoin-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            bitacross-worker-3:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_integration_test.sh sign_bitcoin.test.ts 2>&1' "
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
