[package]
name = "itp-stf-state-handler"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { workspace = true, optional = true }
sgx_types = { workspace = true }

# local dependencies
itp-hashing = { workspace = true }
itp-settings = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-sgx-externalities = { workspace = true }
itp-sgx-io = { workspace = true }
itp-stf-interface = { workspace = true }
itp-stf-state-observer = { workspace = true }
itp-time-utils = { workspace = true }
itp-types = { workspace = true }

# for tests
itp-sgx-temp-dir = { version = "0.1", default-features = false, optional = true, path = "../../core-primitives/sgx/temp-dir" }

# sgx enabled external libraries
rust-base58_sgx = { package = "rust-base58", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rust-base58-sgx", optional = true, default-features = false, features = ["mesalock_sgx"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
rust-base58 = { package = "rust-base58", version = "0.0.4", optional = true }
thiserror = { version = "1.0", optional = true }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[dev-dependencies]
itp-sgx-crypto = { path = "../../core-primitives/sgx/crypto", features = ["mocks"] }
itp-stf-state-observer = { path = "../stf-state-observer", features = ["mocks"] }
itp-hashing = { path = "../../core-primitives/hashing", features = ["std"] }

[features]
default = ["std"]
std = [
    "rust-base58",
    "itp-sgx-crypto/std",
    "itp-sgx-externalities/std",
    "itp-sgx-io/std",
    "itp-stf-interface/std",
    "itp-stf-state-observer/std",
    "itp-time-utils/std",
    "itp-types/std",
    "thiserror",
    "log/std",
]
sgx = [
    "sgx_tstd",
    "rust-base58_sgx",
    "itp-sgx-crypto/sgx",
    "itp-sgx-externalities/sgx",
    "itp-sgx-io/sgx",
    "itp-stf-state-observer/sgx",
    "itp-time-utils/sgx",
    "thiserror_sgx",
]
test = [
    "itp-sgx-crypto/mocks",
    "itp-stf-interface/mocks",
    "itp-sgx-temp-dir",
]
