[package]
name = "lc-vc-task-receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { workspace = true, optional = true }
futures_sgx = { workspace = true, features = ["thread-pool"], optional = true }
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }

codec = { package = "parity-scale-codec", workspace = true }
log = { workspace = true }
sp-core = { workspace = true, features = ["full_crypto"] }

ita-sgx-runtime = { package = "id-ita-sgx-runtime", path = "../../../../app-libs/sgx-runtime", default-features = false }
ita-stf = { package = "id-ita-stf", path = "../../../../app-libs/stf", default-features = false }
itp-enclave-metrics = { workspace = true }
itp-extrinsics-factory = { workspace = true }
itp-node-api = { workspace = true }
itp-ocall-api = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-sgx-externalities = { workspace = true }
itp-stf-executor = { package = "id-itp-stf-executor", path = "../../../../core-primitives/stf-executor", default-features = false }
itp-stf-primitives = { workspace = true }
itp-stf-state-handler = { workspace = true }
itp-storage = { workspace = true }
itp-top-pool-author = { package = "id-itp-top-pool-author", path = "../../../../core-primitives/top-pool-author", default-features = false }
itp-types = { workspace = true }

frame-support = { workspace = true }
lc-dynamic-assertion = { workspace = true }
lc-evm-dynamic-assertions = { workspace = true }
lc-stf-task-receiver = { workspace = true }
lc-stf-task-sender = { workspace = true }
lc-vc-task-sender = { workspace = true }
litentry-macros = { workspace = true }
litentry-primitives = { workspace = true }
pallet-identity-management-tee = { workspace = true }

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "sgx_tstd",
    "ita-stf/sgx",
    "itp-sgx-externalities/sgx",
    "itp-stf-executor/sgx",
    "itp-stf-state-handler/sgx",
    "itp-top-pool-author/sgx",
    "sp-core/full_crypto",
    "litentry-primitives/sgx",
    "lc-stf-task-receiver/sgx",
    "lc-stf-task-sender/sgx",
    "itp-node-api/sgx",
    "itp-storage/sgx",
    "itp-extrinsics-factory/sgx",
    "lc-vc-task-sender/sgx",
    "lc-dynamic-assertion/sgx",
    "lc-evm-dynamic-assertions/sgx",
]
std = [
    "futures",
    "log/std",
    "ita-stf/std",
    "itp-types/std",
    "itp-top-pool-author/std",
    "itp-stf-executor/std",
    "itp-stf-state-handler/std",
    "itp-stf-primitives/std",
    "itp-extrinsics-factory/std",
    "sp-core/std",
    "litentry-primitives/std",
    "ita-sgx-runtime/std",
    "frame-support/std",
    "lc-stf-task-receiver/std",
    "lc-stf-task-sender/std",
    "itp-node-api/std",
    "itp-storage/std",
    "lc-vc-task-sender/std",
    "lc-dynamic-assertion/std",
    "lc-evm-dynamic-assertions/std",
]
development = [
    "ita-stf/development",
    "litentry-macros/development",
    "pallet-identity-management-tee/development",
]
