[package]
name = "itp-utils"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
homepage = "https://litentry.com/"
repository = "https://github.com/litentry/litentry-parachain"
license = "Apache-2.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
hex = { workspace = true }
litentry-hex-utils = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "hex/std",
]
