[workspace]
members = [
    "executor-core",
    "executor-worker",
    "parentchain/listener",
    "ethereum/intention-executor",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
log = "0.4.22"
tokio = "1.40.0"
async-trait = "0.1.82"
env_logger = "0.11.5"
scale-encode = "0.7.1"
parity-scale-codec = "3.6.12"
alloy = "0.3.6"
clap = "4.5.17"
