[package]
name = "itp-enclave-api"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
hex = "0.4"
log = "0.4"
serde_json = "1.0"
thiserror = "1.0.25"

sgx_crypto = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", default-features = false, features = ["ucrypto"] }
sgx_serialize = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", default-features = false, features = ["userialize"] }
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview" }
sgx_urts = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", optional = true }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

itc-parentchain = { path = "../../core/parentchain/parentchain-crate" }
itp-enclave-api-ffi = { path = "ffi" }
itp-settings = { path = "../settings" }
itp-stf-interface = { path = "../stf-interface" }
itp-storage = { path = "../storage" }
itp-types = { path = "../types" }

# litentry
pallet-teebag = { path = "../../../pallets/teebag", default-features = false }

[features]
default = []
implement-ffi = [
    "sgx_urts",
    "itp-enclave-api-ffi/link-sgx-libs",
]
