[package]
name = "itc-parentchain"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "chain-error"] }

# Parity
sp-runtime = { workspace = true }

# local
itc-parentchain-block-import-dispatcher = { workspace = true }
itc-parentchain-block-importer = { workspace = true }
itc-parentchain-indirect-calls-executor = { workspace = true }
itc-parentchain-light-client = { workspace = true }
itp-types = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-runtime/std",
    "itc-parentchain-block-import-dispatcher/std",
    "itc-parentchain-block-importer/std",
    "itc-parentchain-indirect-calls-executor/std",
    "itc-parentchain-light-client/std",
    "itp-types/std",
]
sgx = [
    "itc-parentchain-block-import-dispatcher/sgx",
    "itc-parentchain-block-importer/sgx",
    "itc-parentchain-indirect-calls-executor/sgx",
    "itc-parentchain-light-client/sgx",
]
mocks = [
    "itc-parentchain-block-import-dispatcher/mocks",
    "itc-parentchain-light-client/mocks",
]
test = [
    "mocks",
    "itc-parentchain-light-client/test",
]
