[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-direct-call"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }

# internal dependencies
bc-enclave-registry = { path = "../../../bitacross/core/bc-enclave-registry", default-features = false }
bc-musig2-ceremony = { path = "../../../bitacross/core/bc-musig2-ceremony", default-features = false }
bc-relayer-registry = { path = "../../../bitacross/core/bc-relayer-registry", default-features = false }
bc-signer-registry = { path = "../../../bitacross/core/bc-signer-registry", default-features = false }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-stf-primitives = { path = "../../../core-primitives/stf-primitives", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }
parentchain-primitives = { package = "core-primitives", path = "../../../../primitives/core", default-features = false }

log = { version = "0.4", default-features = false }

# sgx dependencies
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", optional = true }

[dev-dependencies]
k256 = { version = "0.13.3", features = ["ecdsa-core", "schnorr"] }
rand = { version = "0.7" }
hex = { version = "0.4" }

[features]
default = ["std"]
development = [
    "parentchain-primitives/development",
]
sgx = [
    "sgx_tstd",
    "bc-musig2-ceremony/sgx",
    "bc-enclave-registry/sgx",
    "bc-relayer-registry/sgx",
    "bc-signer-registry/sgx",
    "litentry-primitives/sgx",
    "itp-sgx-crypto/sgx",
]
std = [
    "bc-musig2-ceremony/std",
    "bc-enclave-registry/std",
    "bc-relayer-registry/std",
    "bc-signer-registry/std",
    "itp-stf-primitives/std",
    "itp-sgx-crypto/std",
    "litentry-primitives/std",
    "sp-core/std",
    "sp-io/std",
    "parentchain-primitives/std",
]
test = [
    "itp-sgx-crypto/mocks",
]
