services:
  relaychain-alice:
    image: docker_relaychain-alice:latest
    networks:
      - litentry-test-network
    ports:
      - 9946:9944
      - 9936:9933
      - 30336:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: litentry
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  relaychain-bob:
    image: docker_relaychain-bob:latest
    networks:
      - litentry-test-network
    ports:
      - 9947:9944
      - 9937:9933
      - 30337:30333
    volumes:
      - relaychain-bob:/data
    build:
      context: litentry
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
    ulimits: *a1
  litentry-node:
    image: docker_litentry-node:latest
    container_name: litentry-node
    networks:
      - litentry-test-network
    ports:
      # TODO: maybe not use 9912 as port
      - 9944:9912
      - 9933:9933
      - 30333:30333
    volumes:
      - parachain-2106-0:/data
    build:
      context: litentry
      dockerfile: parachain-2106.Dockerfile
    depends_on: ['relaychain-alice', 'relaychain-bob']
    healthcheck:
      test: ["CMD", "nc", "-z", "litentry-node", "9912"]
      interval: 30s
      timeout: 10s
      retries: 20
    command:
      - --base-path=/data
      - --chain=/app/rococo-dev-2106.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2106-0
      - --ws-port=9912
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --alice
      - --node-key=e998e728d8bf5bff6670c5e2b20455f6de1742b7ca564057680c9781cf037dd1
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
    environment:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug

    ulimits: *a1
  bitacross-worker-1:
    image: litentry/bitacross-worker:latest
    container_name: bitacross-worker-1
    build:
      context: ${PWD}/..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on:
      litentry-node:
        condition: service_healthy
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    environment:
      - RUST_LOG=info,litentry_worker=debug,ws=warn,sp_io=error,substrate_api_client=warn,itc_parentchain_light_client=info,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=debug,ita_stf=debug,its_rpc_handler=warn,itc_rpc_client=warn,its_consensus_common=debug,its_state=warn,its_consensus_aura=warn,aura*=warn,its_consensus_slots=warn,itp_attestation_handler=debug,http_req=debug,lc_mock_server=warn,itc_rest_client=debug,lc_credentials=debug,lc_identity_verification=debug,lc_stf_task_receiver=debug,lc_stf_task_sender=debug,lc_data_providers=debug,itp_top_pool=debug,itc_parentchain_indirect_calls_executor=debug,
      - TWITTER_OFFICIAL_URL=http://localhost:19527
      - TWITTER_AUTH_TOKEN_V2=
      - DISCORD_OFFICIAL_URL=http://localhost:19527
      - LITENTRY_DISCORD_MICROSERVICE_URL=http://localhost:19527
      - DISCORD_AUTH_TOKEN=
      - ACHAINABLE_URL=http://localhost:19527
      - ACHAINABLE_AUTH_KEY=
      - CREDENTIAL_ENDPOINT=http://localhost:9933
      - ONEBLOCK_NOTION_KEY=
      - ONEBLOCK_NOTION_URL=http://localhost:19527
      - SORA_QUIZ_MASTER_ID=SORA_QUIZ_MASTER_ID
      - SORA_QUIZ_ATTENDEE_ID=SORA_QUIZ_ATTENDEE_ID
      - MORALIS_API_URL=http://localhost:19527/moralis/
      - MORALIS_SOLANA_API_URL=http://localhost:19527/moralis_solana/
      - KARAT_DAO_API_URL=http://localhost:19527/karat_dao/
      - MAGIC_CRAFT_API_URL=http://localhost:19527/magic_craft/
      - MAGIC_CRAFT_API_KEY=
      - MORALIS_API_KEY=
      - NODEREAL_API_KEY=NODEREAL_API_KEY
      - NODEREAL_API_URL=http://localhost:19527
      - NODEREAL_API_CHAIN_NETWORK_URL=http://localhost:19527/nodereal_jsonrpc/
      - GENIIDATA_URL=http://localhost:19527
      - CONTEST_LEGEND_DISCORD_ROLE_ID=CONTEST_LEGEND_DISCORD_ROLE_ID
      - CONTEST_POPULARITY_DISCORD_ROLE_ID=CONTEST_POPULARITY_DISCORD_ROLE_ID
      - CONTEST_PARTICIPANT_DISCORD_ROLE_ID=CONTEST_PARTICIPANT_DISCORD_ROLE_ID
      - BLOCKCHAIN_INFO_API_URL=http://localhost:19527/blockchain_info/
    networks:
      - litentry-test-network
    healthcheck:
      test: curl -s -f http://bitacross-worker-1:4645/is_initialized || exit 1
      interval: 30s
      timeout: 10s
      retries: 20
    entrypoint:
      "/usr/local/bin/bitacross-worker --clean-reset --ws-external -M bitacross-worker-1 -T wss://bitacross-worker-1
      -u ws://litentry-node -U ws://bitacross-worker-1 -P 2011 -w 2101 -p 9912 -h 4645
      run --dev --skip-ra"
    restart: "no"
  bitacross-worker-2:
    image: litentry/bitacross-worker:latest
    container_name: bitacross-worker-2
    build:
      context: ${PWD}/..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on:
      litentry-node:
        condition: service_healthy
      bitacross-worker-1:
        condition: service_healthy
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    environment:
      - RUST_LOG=info,litentry_worker=debug,ws=warn,sp_io=error,substrate_api_client=warn,itc_parentchain_light_client=info,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=debug,ita_stf=debug,its_rpc_handler=warn,itc_rpc_client=warn,its_consensus_common=debug,its_state=warn,its_consensus_aura=warn,aura*=warn,its_consensus_slots=warn,itp_attestation_handler=debug,http_req=debug,lc_mock_server=warn,itc_rest_client=debug,lc_credentials=debug,lc_identity_verification=debug,lc_stf_task_receiver=debug,lc_stf_task_sender=debug,lc_data_providers=debug,itp_top_pool=debug,itc_parentchain_indirect_calls_executor=debug,
      - TWITTER_OFFICIAL_URL=http://localhost:19527
      - TWITTER_AUTH_TOKEN_V2=
      - DISCORD_OFFICIAL_URL=http://localhost:19527
      - LITENTRY_DISCORD_MICROSERVICE_URL=http://localhost:19527
      - DISCORD_AUTH_TOKEN=
      - ACHAINABLE_URL=http://localhost:19527
      - ACHAINABLE_AUTH_KEY=
      - CREDENTIAL_ENDPOINT=http://localhost:9933
      - ONEBLOCK_NOTION_KEY=
      - ONEBLOCK_NOTION_URL=http://localhost:19527
      - SORA_QUIZ_MASTER_ID=SORA_QUIZ_MASTER_ID
      - SORA_QUIZ_ATTENDEE_ID=SORA_QUIZ_ATTENDEE_ID
      - MORALIS_API_URL=http://localhost:19527/moralis/
      - MORALIS_SOLANA_API_URL=http://localhost:19527/moralis_solana/
      - KARAT_DAO_API_URL=http://localhost:19527/karat_dao/
      - MAGIC_CRAFT_API_URL=http://localhost:19527/magic_craft/
      - MAGIC_CRAFT_API_KEY=
      - MORALIS_API_KEY=
      - NODEREAL_API_KEY=NODEREAL_API_KEY
      - NODEREAL_API_URL=http://localhost:19527
      - NODEREAL_API_CHAIN_NETWORK_URL=http://localhost:19527/nodereal_jsonrpc/
      - GENIIDATA_URL=http://localhost:19527
      - CONTEST_LEGEND_DISCORD_ROLE_ID=CONTEST_LEGEND_DISCORD_ROLE_ID
      - CONTEST_POPULARITY_DISCORD_ROLE_ID=CONTEST_POPULARITY_DISCORD_ROLE_ID
      - CONTEST_PARTICIPANT_DISCORD_ROLE_ID=CONTEST_PARTICIPANT_DISCORD_ROLE_ID
      - BLOCKCHAIN_INFO_API_URL=http://localhost:19527/blockchain_info/
    networks:
      - litentry-test-network
    healthcheck:
      test: curl -s -f http://bitacross-worker-2:4645/is_initialized || exit 1
      interval: 30s
      timeout: 10s
      retries: 20
    entrypoint:
      "/usr/local/bin/bitacross-worker --clean-reset --ws-external -M bitacross-worker-2 -T wss://bitacross-worker-2
      -u ws://litentry-node -U ws://litentry-worker-2 -P 2011 -w 2101 -p 9912 -h 4645
      run --dev --skip-ra --request-state"
    restart: "no"
  litentry-worker-3:
    image: litentry/litentry-worker:latest
    container_name: litentry-worker-3
    build:
      context: ${PWD}/..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on:
      litentry-node:
        condition: service_healthy
      litentry-worker-2:
        condition: service_healthy
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    environment:
      - RUST_LOG=info,litentry_worker=debug,ws=warn,sp_io=error,substrate_api_client=warn,itc_parentchain_light_client=info,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=debug,ita_stf=debug,its_rpc_handler=warn,itc_rpc_client=warn,its_consensus_common=debug,its_state=warn,its_consensus_aura=warn,aura*=warn,its_consensus_slots=warn,itp_attestation_handler=debug,http_req=debug,lc_mock_server=warn,itc_rest_client=debug,lc_credentials=debug,lc_identity_verification=debug,lc_stf_task_receiver=debug,lc_stf_task_sender=debug,lc_data_providers=debug,itp_top_pool=debug,itc_parentchain_indirect_calls_executor=debug,
      - TWITTER_OFFICIAL_URL=http://localhost:19527
      - TWITTER_AUTH_TOKEN_V2=
      - DISCORD_OFFICIAL_URL=http://localhost:19527
      - LITENTRY_DISCORD_MICROSERVICE_URL=http://localhost:19527
      - DISCORD_AUTH_TOKEN=
      - ACHAINABLE_URL=http://localhost:19527
      - ACHAINABLE_AUTH_KEY=
      - CREDENTIAL_ENDPOINT=http://localhost:9933
      - ONEBLOCK_NOTION_KEY=
      - ONEBLOCK_NOTION_URL=http://localhost:19527
      - SORA_QUIZ_MASTER_ID=SORA_QUIZ_MASTER_ID
      - SORA_QUIZ_ATTENDEE_ID=SORA_QUIZ_ATTENDEE_ID
      - MORALIS_API_URL=http://localhost:19527/moralis/
      - MORALIS_SOLANA_API_URL=http://localhost:19527/moralis_solana/
      - KARAT_DAO_API_URL=http://localhost:19527/karat_dao/
      - MAGIC_CRAFT_API_URL=http://localhost:19527/magic_craft/
      - MAGIC_CRAFT_API_KEY=
      - MORALIS_API_KEY=
      - NODEREAL_API_KEY=NODEREAL_API_KEY
      - NODEREAL_API_URL=http://localhost:19527
      - NODEREAL_API_CHAIN_NETWORK_URL=http://localhost:19527/nodereal_jsonrpc/
      - GENIIDATA_URL=http://localhost:19527
      - CONTEST_LEGEND_DISCORD_ROLE_ID=CONTEST_LEGEND_DISCORD_ROLE_ID
      - CONTEST_POPULARITY_DISCORD_ROLE_ID=CONTEST_POPULARITY_DISCORD_ROLE_ID
      - CONTEST_PARTICIPANT_DISCORD_ROLE_ID=CONTEST_PARTICIPANT_DISCORD_ROLE_ID
      - BLOCKCHAIN_INFO_API_URL=http://localhost:19527/blockchain_info/
    networks:
      - litentry-test-network
    healthcheck:
      test: curl -s -f http://litentry-worker-3:4645/is_initialized || exit 1
      interval: 30s
      timeout: 10s
      retries: 20
    entrypoint:
      "/usr/local/bin/litentry-worker --clean-reset --ws-external -M litentry-worker-3 -T wss://litentry-worker-3
      -u ws://litentry-node -U ws://litentry-worker-3 -P 2011 -w 2101 -p 9912 -h 4645
      run --dev --skip-ra --request-state"
    restart: "no"
volumes:
  ? relaychain-alice
  ? relaychain-bob
  ? parachain-2106-0
networks:
  litentry-test-network:
    driver: bridge
