[package]
name = "itp-settings"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]

[features]
production = [
]
offchain-worker = []
