[package]
name = "its-rpc-handler"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# local dependencies
itp-rpc = { path = "../../core-primitives/rpc", default-features = false }
itp-stf-primitives = { path = "../../core-primitives/stf-primitives", default-features = false }
itp-top-pool-author = { path = "../../core-primitives/top-pool-author", default-features = false }
itp-types = { path = "../../core-primitives/types", default-features = false }
itp-utils = { path = "../../core-primitives/utils", default-features = false }
its-primitives = { path = "../primitives", default-features = false }

lc-vc-task-sender = { path = "../../litentry/core/vc-task/sender", default-features = false }
litentry-primitives = { path = "../../litentry/primitives", default-features = false }

# sgx enabled external libraries
futures_sgx = { package = "futures", git = "https://github.com/Kailai-Wang/futures-rs-sgx", branch = "sgx-sdk-2.0.0", optional = true }
jsonrpc-core_sgx = { package = "jsonrpc-core", git = "https://github.com/Kailai-Wang/jsonrpc-sgx", branch = "sgx-sdk-2.0.0", default-features = false, optional = true }
rust-base58_sgx = { package = "rust-base58", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rust-base58-sgx", optional = true, default-features = false, features = ["mesalock_sgx"] }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
futures = { version = "0.3", optional = true }
jsonrpc-core = { version = "18", optional = true }
rust-base58 = { package = "rust-base58", version = "0.0.4", optional = true }

# no-std compatible libraries
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[features]
default = ["std"]
std = [
    "futures",
    "itp-rpc/std",
    "itp-stf-primitives/std",
    "itp-top-pool-author/std",
    "itp-types/std",
    "its-primitives/std",
    "litentry-primitives/std",
    "jsonrpc-core",
    "log/std",
    "rust-base58",
    "lc-vc-task-sender/std",
]
sgx = [
    "futures_sgx",
    "sgx_tstd",
    "itp-rpc/sgx",
    "itp-top-pool-author/sgx",
    "jsonrpc-core_sgx",
    "rust-base58_sgx",
    "lc-vc-task-sender/sgx",
]
