[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-identity-verification"
version = "0.1.0"

[dependencies]
# std dependencies
hex = { version = "0.4.3", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true }
hex-sgx = { package = "hex", git = "https://github.com/mesalock-linux/rust-hex-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
http-sgx = { package = "http", git = "https://github.com/integritee-network/http-sgx.git", branch = "sgx-experimental", optional = true }
http_req-sgx = { package = "http_req", git = "https://github.com/integritee-network/http_req", default-features = false, features = ["rust-tls", "sgx"], optional = true }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
log = { version = "0.4", default-features = false }

# internal dependencies
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }

lc-data-providers = { path = "../data-providers", default-features = false }
lc-stf-task-sender = { path = "../stf-task/sender", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "hex-sgx",
    "http-sgx",
    "http_req-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
    "itp-sgx-crypto/sgx",
    "lc-data-providers/sgx",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
]
std = [
    "hex",
    "log/std",
    "itp-sgx-crypto/std",
    "frame-support/std",
    "lc-data-providers/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
]
