[package]
name = "lc-vc-task-sender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std dependencies
futures = { version = "0.3", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/Kailai-Wang/futures-rs-sgx", branch = "sgx-sdk-2.0.0", optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "thread"], optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }

# substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }

# internal dependencies
itp-types = { path = "../../../../core-primitives/types", default-features = false }

# litentry
lc-stf-task-sender = { path = "../../stf-task/sender", default-features = false }
litentry-primitives = { path = "../../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "sgx_tstd",
    "lc-stf-task-sender/sgx",
]
std = [
    "futures",
    "log/std",
    "sp-runtime/std",
    "sp-std/std",
    "itp-types/std",
    "lc-stf-task-sender/std",
]
