[package]
name = "itc-direct-rpc-client"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = "2021"

[dependencies]
# sgx dependencies
rustls_sgx = { package = "rustls", optional = true, git = "https://github.com/Kailai-Wang/rustls-sgx", branch = "sgx-sdk-2.0.0", features = ["dangerous_configuration"] }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
tungstenite_sgx = { package = "tungstenite", optional = true, git = "https://github.com/Kailai-Wang/tungstenite-rs-sgx", branch = "sgx-sdk-2.0.0", features = ["rustls-tls-webpki-roots"] }
webpki_sgx = { package = "webpki", optional = true, git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
log = { version = "0.4", default-features = false }
serde_json = { version = "1.0", default-features = false }
url = { git = "https://github.com/domenukk/rust-url", branch = "no_std", default-features = false, features = ["alloc", "no_std_net"] }

# std dependencies
rustls = { version = "0.19", optional = true, features = ["dangerous_configuration"] }
tungstenite = { version = "0.15.0", optional = true, features = ["rustls-tls-webpki-roots"] }
webpki = { version = "0.21", optional = true }

# local dependencies
itp-rpc = { path = "../../core-primitives/rpc", default-features = false }
itp-types = { path = "../../core-primitives/types", default-features = false }
itp-utils = { path = "../../core-primitives/utils", default-features = false }
litentry-primitives = { path = "../../litentry/primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "webpki_sgx",
    "tungstenite_sgx",
    "rustls_sgx",
    "sgx_tstd",
    "itp-rpc/sgx",
    "litentry-primitives/sgx",
]
std = [
    "rustls",
    "webpki",
    "tungstenite",
    "url/std",
    "itp-rpc/std",
    "itp-types/std",
    "itp-utils/std",
    "log/std",
    "litentry-primitives/std",
]
