[package]
name = "itc-rest-client"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# std dependencies
http = { version = "0.2", optional = true }
http_req = { optional = true, features = ["rust-tls"], branch = "master", git = "https://github.com/integritee-network/http_req" }
thiserror = { version = "1.0.26", optional = true }

# sgx dependencies
http-sgx = { package = "http", git = "https://github.com/integritee-network/http-sgx.git", branch = "sgx-experimental", optional = true }
http_req-sgx = { optional = true, default-features = false, features = ["rust-tls", "sgx"], package = "http_req", git = "https://github.com/integritee-network/http_req" }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
url = { git = "https://github.com/domenukk/rust-url", branch = "no_std", default-features = false, features = ["alloc", "no_std_net"] }

[features]
default = ["std"]
std = [
    # std only
    "http",
    "http_req",
    "thiserror",
    # no_std
    "base64/std",
    "serde/std",
    "serde_json/std",
    "log/std",
    "url/std",
]
sgx = [
    "http-sgx",
    "http_req-sgx",
    "sgx_tstd",
    "thiserror_sgx",
]
