[package]
name = "itp-sgx-runtime-primitives"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]

# Substrate dependencies
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# litentry
litentry-primitives = { path = "../../litentry/primitives", default-features = false }

[features]
default = ["std"]
std = [
    "frame-system/std",
    "pallet-balances/std",
    "sp-core/std",
    "sp-runtime/std",
    # litentry
    "litentry-primitives/std",
]
