[package]
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"
homepage = "https://integritee.network/"
license = "Apache-2.0"
name = "common-primitives"
repository = "https://github.com/integritee-network/pallets/"
version = "0.1.0"

[dependencies]

# substrate deps
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }

[features]
default = ["std"]
std = [
  "sp-std/std",
]
