[package]
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"
homepage = "https://integritee.network/"
license = "Apache-2.0"
name = "teerex-primitives"
repository = "https://github.com/integritee-network/pallets/"
version = "0.1.0"

[dependencies]
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
common-primitives = { path = "../common", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.159", default-features = false }

# substrate dependencies
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

[dev-dependencies]
hex-literal = "0.4.1"

[features]
default = ["std"]
std = [
  "codec/std",
  "common-primitives/std",
  "scale-info/std",
  "serde/std",
  # substrate
  "sp-core/std",
  "sp-io/std",
  "sp-std/std",
]
