[package]
authors = ['Litentry Dev']
description = 'FRAME pallet template for defining custom runtime logic.'
edition = '2021'
homepage = 'https://litentry.com'
license = 'Unlicense'
name = 'pallet-sgx-account-linker'
repository = 'https://github.com/litentry/litentry-pallets'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
log = { version = "0.4", default-features = false }
ripemd160 = { default-features = false, version = "0.9.1" }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sha2 = { default-features = false, version = "0.9.5" }
# no_std
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "chain-error"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32" }

[dev-dependencies]
bitcoin = { version = "0.25.2", features = ["rand"] }
hex = "0.4.3"
parity-crypto = { version = "0.9.0", features = ["publickey"] }
serde = { version = "1.0" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    "sp-io/std",
    "sp-core/std",
    "sp-std/std",
    "sha2/std",
    "ripemd160/std",
    "log/std",
    "scale-info/std",
]
