[package]
name = "id-itc-offchain-worker-executor"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
log = { workspace = true }
sgx_tstd = { workspace = true, optional = true }

thiserror = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

itc-parentchain-light-client = { workspace = true }
itp-extrinsics-factory = { workspace = true }
itp-stf-executor = { package = "id-itp-stf-executor", path = "../../core-primitives/stf-executor", default-features = false }
itp-stf-interface = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-stf-state-handler = { workspace = true }
itp-top-pool-author = { package = "id-itp-top-pool-author", path = "../../core-primitives/top-pool-author", default-features = false }
itp-types = { workspace = true }

sp-runtime = { workspace = true }

[dev-dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = ["std"] }
itc-parentchain-light-client = { workspace = true, features = ["std", "mocks"] }
itp-extrinsics-factory = { workspace = true, features = ["std", "mocks"] }
itp-stf-executor = { package = "id-itp-stf-executor", path = "../../core-primitives/stf-executor", features = ["std", "mocks"] }
itp-test = { workspace = true, features = ["std"] }
itp-top-pool-author = { package = "id-itp-top-pool-author", path = "../../core-primitives/top-pool-author", features = ["std", "mocks"] }
itp-stf-interface = { workspace = true, features = ["std", "mocks"] }
itp-sgx-externalities = { workspace = true }
sp-core = { workspace = true, features = ["full_crypto"] }

[features]
default = ["std"]
std = [
    "itc-parentchain-light-client/std",
    "itp-extrinsics-factory/std",
    "itp-stf-executor/std",
    "itp-stf-interface/std",
    "itp-stf-primitives/std",
    "itp-stf-state-handler/std",
    "itp-top-pool-author/std",
    "itp-types/std",
    "sp-runtime/std",
    "thiserror",
]
sgx = [
    "itc-parentchain-light-client/sgx",
    "itp-extrinsics-factory/sgx",
    "itp-stf-executor/sgx",
    "itp-stf-state-handler/sgx",
    "itp-top-pool-author/sgx",
    "sgx_tstd",
    "thiserror_sgx",
]
