[package]
name = "id-ita-stf"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
log = { workspace = true }
rlp = { workspace = true }
sha3 = { workspace = true }

sgx_tstd = { workspace = true, features = ["untrusted_fs", "net", "backtrace"], optional = true }

itp-hashing = { workspace = true }
itp-node-api = { workspace = true }
itp-node-api-metadata = { workspace = true }
itp-sgx-externalities = { workspace = true }
itp-stf-interface = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-storage = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

ita-sgx-runtime = { package = "id-ita-sgx-runtime", path = "../sgx-runtime", default-features = false }
sp-io = { path = "../../../common/core-primitives/substrate-sgx/sp-io", default-features = false, features = ["disable_oom", "disable_panic_handler", "disable_allocator"] }

frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-sudo = { workspace = true }
sp-core = { workspace = true, features = ["full_crypto"] }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# litentry
itp-node-api-metadata-provider = { workspace = true }
lc-stf-task-sender = { path = "../../litentry/core/stf-task/sender", default-features = false }
litentry-hex-utils = { workspace = true }
litentry-macros = { workspace = true }
litentry-primitives = { workspace = true }
pallet-parentchain = { workspace = true }

[dev-dependencies]
sp-keyring = { workspace = true }

[features]
default = ["std"]
evm = ["ita-sgx-runtime/evm"]
sgx = [
    "sgx_tstd",
    "itp-sgx-externalities/sgx",
    "sp-io/sgx",
    "itp-node-api/sgx",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
    "itp-node-api-metadata-provider/sgx",
]
std = [
    "codec/std",
    "log/std",
    "ita-sgx-runtime/std",
    "itp-hashing/std",
    "itp-sgx-externalities/std",
    "itp-stf-interface/std",
    "itp-storage/std",
    "itp-types/std",
    "itp-node-api/std",
    "itp-node-api-metadata/std",
    "sp-core/std",
    "pallet-balances/std",
    "pallet-sudo/std",
    "frame-system/std",
    "frame-support/std",
    "sp-runtime/std",
    "pallet-parentchain/std",
    "sp-io/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
    "itp-node-api-metadata-provider/std",
]
test = []
development = [
    "litentry-macros/development",
    "ita-sgx-runtime/development",
]
