[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-stf-task-sender"
version = "0.1.0"

[dependencies]
# std dependencies
thiserror = { version = "1.0.26", optional = true }
url = { version = "2.0.0", optional = true }

# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }

# substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39", default-features = false }

# internal dependencies
itp-types = { path = "../../../../core-primitives/types", default-features = false }

# litentry
itp-stf-primitives = { default-features = false, path = "../../../../core-primitives/stf-primitives" }
litentry-primitives = { path = "../../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
]
std = [
    "log/std",
    "sp-runtime/std",
    "sp-std/std",
    "thiserror",
    "url",
    "itp-types/std",
]
