[package]
authors = ["Integritee AG <hello@integritee.network>"]
description = "a certificate verification and IAS report parser crate for the teerex pallet"
edition = "2021"
homepage = "https://integritee.network/"
license = "GPL-3.0"
name = "sgx-verify"
repository = "https://github.com/integritee-network/pallets/"
version = "0.1.4"

[dependencies]
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
der = { default-features = false, version = "0.6.0" }
hex = { default-features = false, version = "0.4.3", features = ["alloc"] }
ring = { git = "https://github.com/Niederb/ring-xous.git", branch = "0.16.20-cleanup", default-features = false, features = ["alloc"] }
scale-info = { version = "2.4.0", default-features = false, features = ["derive"] }
serde = { default-features = false, version = "1.0.140", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
webpki = { default-features = false, git = "https://github.com/scs/webpki-nostd.git", branch = "master" }
x509-cert = { default-features = false, version = "0.1.0", features = ["alloc"] }

# local
teerex-primitives = { path = "../../../primitives/teerex", default-features = false }

# substrate dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

[dev-dependencies]
hex-literal = "0.3.4"

[features]
default = ["std"]
std = [
  "base64/std",
  "chrono/std",
  "codec/std",
  "der/std",
  "hex/std",
  "ring/std",
  "scale-info/std",
  "serde/std",
  "serde_json/std",
  "webpki/std",
  "x509-cert/std",
  # local
  "teerex-primitives/std",
  # substrate
  "frame-support/std",
  "sp-core/std",
  "sp-io/std",
  "sp-std/std",
]
