[package]
name = "itp-time-utils"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["alloc"], optional = true }

chrono_sgx = { package = "chrono", git = "https://github.com/mesalock-linux/chrono-sgx", optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[features]
default = ["std"]
std = [
    "chrono",
]
sgx = [
    "sgx_tstd",
    "chrono_sgx",
]
