[package]
authors = ["Integritee AG <hello@integritee.network>"]
description = "The remote attestation registry and verification pallet for integritee blockchains and parachains"
edition = "2021"
homepage = "https://integritee.network/"
license = "Apache-2.0"
name = "pallet-teerex"
repository = "https://github.com/integritee-network/pallets/"
version = "0.9.0"

[dependencies]
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", features = ["derive"], optional = true }

# local
sgx-verify = { path = "./sgx-verify", default-features = false }
teerex-primitives = { path = "../../primitives/teerex", default-features = false }

# substrate dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
timestamp = { package = "pallet-timestamp", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

# benchmarking
frame-benchmarking = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
hex-literal = { version = "0.4.1", optional = true }
pallet-balances = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
test-utils = { path = "../test-utils", default-features = false, optional = true }

[dev-dependencies]
env_logger = "0.10.0"
externalities = { package = "sp-externalities", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
hex-literal = "0.4.1"
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
test-utils = { path = "../test-utils" }

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking",
  "hex-literal",
  "pallet-balances",
  "test-utils",
  "timestamp/runtime-benchmarks",
]
std = [
  "codec/std",
  "log/std",
  "scale-info/std",
  "serde",
  # local
  "sgx-verify/std",
  "teerex-primitives/std",
  # substrate
  "frame-support/std",
  "frame-system/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "timestamp/std",
]
# allow workers to register without remote attestation for dev purposes
skip-ias-check = []
# allow workers to register without checking the scheduled enclave, should only used in dev/tests
skip-scheduled-enclave-check = []

try-runtime = ["frame-support/try-runtime"]
