name: Tee-worker CI

# this is a modified version of tee-worker/.github/workflows/build_and_test.yml with
# extra triggering control.
#
# the original file (`tee-worker/.github/workflows/build_and_test.yml`) is kept to sync
# upstream changes, therefore we need to manually apply the changes to this file.

# tried symbolic link -- didn't work, see https://stackoverflow.com/a/71704019

on:
  workflow_dispatch:
  push:
    branches:
      - tee-dev
  pull_request:
    branches:
      - tee-dev

env:
  CARGO_TERM_COLOR: always
  LOG_DIR: logs
  BUILD_CONTAINER_NAME: integritee_worker_enclave_test
  UPLOAD_DOWNLOAD_DIR_PREFIX: /tmp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# to minimise the changes by setting a default working directory
# please note it only applies to the `run` command, not `use` command
defaults:
  run:
    working-directory: tee-worker

jobs:
  check-file-change:
    runs-on: ubuntu-latest
    # see https://github.com/orgs/community/discussions/25722
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Checks to see if any files in the PR/commit match one of the listed file types.
      # We can use this filter to decide whether or not to build docker images
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'tee-worker/**'
              - '.github/workflows/tee-worker-ci.yml'

  build-parachain-docker:
    runs-on: ubuntu-latest
    needs: check-file-change
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          ./scripts/litentry/build_parachain_docker.sh

      - name: Save docker image
        run: |
          docker save litentry/litentry-parachain:tee-dev -o ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v3
        with:
          name: parachain-artifact
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar

  build-test:
    runs-on: ubuntu-20.04
    needs: check-file-change
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor_id: sidechain
            mode: sidechain
          - flavor_id: mockserver
            mode: sidechain
            additional_features: mockserver

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver: docker-container

      - name: Build Worker & Run Cargo Test
        env:
          DOCKER_BUILDKIT: 1
        run: >
          cd .. && docker build -t integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }}
          --target deployed-worker
          --build-arg WORKER_MODE_ARG=${{ matrix.mode }} --build-arg ADDITIONAL_FEATURES_ARG=${{ matrix.additional_features }}
          -f tee-worker/build.Dockerfile .

      - name: Build CLI client
        env:
          DOCKER_BUILDKIT: 1
        run: >
          cd .. && docker build -t integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }}
          --target deployed-client
          --build-arg WORKER_MODE_ARG=${{ matrix.mode }} --build-arg ADDITIONAL_FEATURES_ARG=${{ matrix.additional_features }}
          -f tee-worker/build.Dockerfile .

      - run: docker images --all

      - name: Test Enclave # cargo test is not supported in the enclave, see: https://github.com/apache/incubator-teaclave-sgx-sdk/issues/232
        run: docker run --name ${{ env.BUILD_CONTAINER_NAME }} integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }} test --all

      - name: Export worker image(s)
        run: |
          docker image save integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }} | gzip > ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz
          docker image save integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }} | gzip > ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz

      - name: Upload worker image
        uses: actions/upload-artifact@v3
        with:
          name: integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz

      - name: Upload CLI client image
        uses: actions/upload-artifact@v3
        with:
          name: integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz

  clippy:
    runs-on: ubuntu-latest
    needs: check-file-change
    container: "integritee/integritee-dev:0.1.9"
    steps:
      - uses: actions/checkout@v3
      - name: init rust
        # enclave is not in the same workspace
        run: rustup show && cd enclave-runtime && rustup show

      - name: Clippy default features
        run: cargo clippy -- -D warnings
      - name: Enclave # Enclave is separate as it's not in the workspace
        run: cd enclave-runtime && cargo clippy -- -D warnings

      - name: Clippy with EVM feature
        run: |
          cargo clippy --features evm -- -D warnings
          cd enclave-runtime && cargo clippy --features evm -- -D warnings
      - name: Clippy with Sidechain feature
        run: |
          cargo clippy --features sidechain -- -D warnings
          cd enclave-runtime && cargo clippy --features sidechain -- -D warnings
      - name: Clippy with Teeracle feature
        run: |
          cargo clippy --features teeracle -- -D warnings
          cd enclave-runtime && cargo clippy --features teeracle -- -D warnings
      - name: Clippy with Offchain-worker feature
        run: |
          cargo clippy --features offchain-worker -- -D warnings
          cd enclave-runtime && cargo clippy --features offchain-worker -- -D warnings
      - name: Fail-fast; cancel other jobs
        if: failure()
        uses: andymckay/cancel-action@0.2

  fmt:
    runs-on: ubuntu-latest
    needs: check-file-change
    steps:
      - uses: actions/checkout@v3
      - name: init rust
        run: rustup show

      - name: Worker & Client
        run: cargo fmt --all -- --check
      - name: Enclave # Enclave is separate as it's not in the workspace
        run: cd enclave-runtime && cargo fmt --all -- --check

      - name: Install taplo
        run: cargo install taplo-cli --locked
      - name: Cargo.toml fmt
        run: taplo fmt --check

      - name: Fail-fast; cancel other jobs
        if: failure()
        uses: andymckay/cancel-action@0.2

  integration-tests:
    runs-on: ubuntu-20.04
    needs:
      - build-parachain-docker
      - build-test
    env:
      WORKER_IMAGE_TAG: integritee-worker:dev
      CLIENT_IMAGE_TAG: integritee-cli:dev
      COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY }}
      TEERACLE_INTERVAL_SECONDS: 4

    strategy:
      fail-fast: false
      matrix:
        include:
          - test: M6
            flavor_id: sidechain
            demo_name: demo-indirect-invocation
          - test: M8
            flavor_id: sidechain
            demo_name: demo-direct-call
          - test: Sidechain
            flavor_id: sidechain
            demo_name: demo-sidechain
          - test: Benchmark
            flavor_id: sidechain
            demo_name: sidechain-benchmark
          # Litentry
          - test: user-shielding-key
            flavor_id: sidechain
            demo_name: user-shielding-key
          - test: ts-tests
            flavor_id: mockserver
            demo_name: ts-tests

    steps:
      - uses: actions/checkout@v3

      - name: Pull polkadot image
        run: |
          docker pull parity/polkadot:latest

      - uses: actions/download-artifact@v3
        with:
          name: parachain-artifact
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}

      - name: Load docker image
        run: |
          docker load -i ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar

      - name: Download Worker Image
        uses: actions/download-artifact@v3
        with:
          name: integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}

      - name: Download CLI client Image
        uses: actions/download-artifact@v3
        with:
          name: integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}

      - name: Load Worker & Client Images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker image load --input ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz
          docker image load --input ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }}.tar.gz
          docker images --all

      - name: Re-name Image Tags
        run: |
          docker tag integritee-worker-${{ matrix.flavor_id }}-${{ github.sha }} ${{ env.WORKER_IMAGE_TAG }}
          docker tag integritee-cli-client-${{ matrix.flavor_id }}-${{ github.sha }} ${{ env.CLIENT_IMAGE_TAG }}
          docker images --all

      - name: Generate parachain artefacts
        run: |
          ./scripts/litentry/generate_parachain_artefacts.sh

      - name: Build litentry parachain docker images
        run: |
          cd docker
          docker-compose -f litentry-parachain.build.yml build

      - name: Integration Test ${{ matrix.test }}-${{ matrix.flavor_id }}
        timeout-minutes: 30
        run: |
          cd docker
          docker-compose -f docker-compose.yml -f ${{ matrix.demo_name }}.yml up --no-build --exit-code-from ${{ matrix.demo_name }} -- ${{ matrix.demo_name }}

      - name: Stop docker containers
        run: |
          cd docker
          docker compose -f docker-compose.yml -f ${{ matrix.demo_name }}.yml stop

      - name: Collect Docker Logs
        continue-on-error: true
        if: always()
        uses: jwalton/gh-docker-logs@v2
        with:
          #images: '${{ env.WORKER_IMAGE_TAG }},${{ env.CLIENT_IMAGE_TAG }}'
          tail: all
          dest: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/${{ env.LOG_DIR }}

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs-${{ matrix.test }}-${{ matrix.flavor_id }}
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/${{ env.LOG_DIR }}

  # Only push docker image when tests are passed and it's a push event
  push-docker-image:
    runs-on: ubuntu-latest
    needs:
      - integration-tests
    if: ${{ success() && (github.event_name == 'push') }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: parachain-artifact
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}

      - name: Load docker image
        run: |
          docker load -i ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar

      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker image
        run: docker push litentry/litentry-parachain:tee-dev

  release:
    name: Draft Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-test, integration-tests]
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Integritee Service
        uses: actions/download-artifact@v3
        with:
          name: integritee-worker-sidechain-${{ github.sha }}
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-worker-tmp

      - name: Download Integritee Client
        uses: actions/download-artifact@v3
        with:
          name: integritee-client-sidechain-${{ github.sha }}
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-client-tmp

      - name: Download Enclave Signed
        uses: actions/download-artifact@v3
        with:
          name: enclave-signed-sidechain-${{ github.sha }}
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/enclave-signed-tmp

      - name: Move service binaries
        run: mv ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-worker-tmp/integritee-service ./integritee-demo-validateer

      - name: Move service client binaries
        run: mv ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-client-tmp/integritee-cli ./integritee-client

      - name: Move service client binaries
        run: mv ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/enclave-signed-tmp/enclave.signed.so ./enclave.signed.so

      - name: Create required package.json
        run: test -f package.json || echo '{}' >package.json

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .

      - name: Release
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: true
          # note the path change
          files: |
            tee-worker/integritee-client
            tee-worker/integritee-demo-validateer
            tee-worker/enclave.signed.so
