name: Verify the correctness of VC content

on:
  workflow_dispatch:
    inputs:
      docker-tag:
        description: "an existing docker tag (e.g. v0.9.18)"
        required: true
        default: "latest"
  schedule:
    - cron: '0 12 * * 3,6' # Run every Wednesday and Saturday at 12:00 UTC

env:
  DOCKER_TAG: ${{ github.event.inputs.docker-tag || 'latest' }}

jobs:
  test-vc-correctness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull litentry image optionally
        run: |
          docker pull litentry/identity-worker:$DOCKER_TAG
          docker pull litentry/identity-cli:$DOCKER_TAG
          docker pull litentry/litentry-parachain:$DOCKER_TAG

      - name: Re-tag docker image
        run: |
          docker tag litentry/identity-worker:$DOCKER_TAG litentry/identity-worker:latest
          docker tag litentry/identity-cli:$DOCKER_TAG litentry/identity-cli:latest
          docker tag litentry/litentry-parachain:$DOCKER_TAG litentry/litentry-parachain:latest

      - run: docker images --all

      - name: Enable corepack and pnpm
        run: corepack enable && corepack enable pnpm

      - name: Launch parachain network
        run: |
          make launch-network-litentry

      - name: Run vc correctness tests
        working-directory: ./tee-worker/identity/docker
        run: |
          docker compose -f docker-compose.yml -f lit-vc-correctness-test.yml up --no-build --exit-code-from lit-vc-correctness-test lit-vc-correctness-test

      - name: Stop docker containers
        working-directory: ./tee-worker/identity/docker
        run: |
          docker compose -f docker-compose.yml -f lit-vc-correctness-test.yml stop

      - name: Collect Docker Logs
        continue-on-error: true
        if: always()
        uses: jwalton/gh-docker-logs@v2
        with:
          tail: all
          dest: logs

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-lit-vc-correctness-test
          path: logs
          if-no-files-found: ignore
