services:
    lit-twitter-identity-multiworker-test:
        image: litentry/litentry-cli:latest
        container_name: litentry-twitter-identity-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-node:
                condition: service_healthy
            litentry-worker-1:
                condition: service_healthy
            litentry-worker-2:
                condition: service_healthy
            litentry-worker-3:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_integration_test.sh twitter_identity.test.ts 2>&1' "
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
